# Generated by Django 3.2.3 on 2021-06-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='usertname',
            new_name='username',
        ),
    ]
