# Generated by Django 3.2 on 2021-06-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_djangoqank_pythonqbank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoQank',
            new_name='DjangoQBank',
        ),
    ]
